-- schema + table
DROP table IF EXISTS users.Contact;
CREATE SCHEMA IF NOT EXISTS users;


CREATE TABLE contact (
	id int8 GENERATED BY DEFAULT AS IDENTITY( INCREMENT BY 1 MINVALUE 1 MAXVALUE 9223372036854775807 START 1 CACHE 1 NO CYCLE) NOT NULL,
	userid text NULL,
	email text NULL,
	phone text NULL,
	first_name text NULL,
	last_name text NULL,
	is_active bool DEFAULT true NOT NULL,
	created_at text NULL,
	age int4 NULL,
	CONSTRAINT contact_pkey PRIMARY KEY (id)
);
CREATE INDEX idx_users_created_at ON users.contact USING btree (created_at DESC);
CREATE INDEX idx_users_email ON users.contact USING btree (email);
CREATE INDEX idx_users_is_active ON users.contact USING btree (is_active);

INSERT INTO users.Contact (id, userId, email, phone, first_name, last_name, is_active, created_at, age)
VALUES
  ('1',
   'u-22',
   'mstauroy@gmail.com',
   '2109456738',
   'Manthos',
   'Staurou',
   TRUE,
   '2025-10-19T21:00:00Z'::timestamptz,
   35)
ON CONFLICT (id) DO NOTHING;
