DROP TABLE IF EXISTS users.contact;
CREATE SCHEMA IF NOT EXISTS users;

CREATE TABLE users.contact (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    userid TEXT NOT NULL UNIQUE,
    email TEXT NOT NULL,
    phone TEXT,
    first_name TEXT,
    last_name TEXT,
    is_active BOOLEAN NOT NULL DEFAULT TRUE,
    created_at TEXT,
    age INTEGER
);

CREATE INDEX idx_users_created_at ON users.contact (created_at DESC);
CREATE INDEX idx_users_email ON users.contact (email);
CREATE INDEX idx_users_is_active ON users.contact (is_active);

INSERT INTO users.contact (userid, email, phone, first_name, last_name, is_active, created_at, age)
VALUES (
    'u-22',
    'demo@example.com',
    '2109456738',
    'Demo',
    'User',
    TRUE,
    '2025-10-19T21:00:00Z',
    35
)
ON CONFLICT (userid) DO NOTHING;
