server:
  port: 8080

app:
  topic: users.v1

spring:
  kafka:
    bootstrap-servers: localhost:29092
    client-id: user-producer
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: io.confluent.kafka.serializers.KafkaAvroSerializer
      acks: all
    properties:
      schema.registry.url: http://localhost:8081
      auto.register.schemas: true
