server:
  port: 8089

app:
  topic: users.v1

spring:
  datasource:
    url: ${DB_URL:jdbc:postgresql://localhost:5432/users}
    username: ${DB_USERNAME:kafka}
    password: ${DB_PASSWORD:kafkaConfluent}
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: validate
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
    show-sql: false
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true
        jdbc:
          time_zone: UTC

  kafka:
    bootstrap-servers: ${CLOUD_BOOTSTRAP_SERVERS}
    client-id: user-consumer-cloud
    consumer:
      group-id: user-svc
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: io.confluent.kafka.serializers.KafkaAvroDeserializer
      auto-offset-reset: earliest
    properties:
      security.protocol: SASL_SSL
      sasl.mechanism: PLAIN
      sasl.jaas.config: >
        org.apache.kafka.common.security.plain.PlainLoginModule required
        username='${CLOUD_API_KEY}' password='${CLOUD_API_SECRET}';
      schema.registry.url: ${SR_URL}
      basic.auth.credentials.source: USER_INFO
      schema.registry.basic.auth.user.info: ${SR_API_KEY}:${SR_API_SECRET}
      specific.avro.reader: true
      value.subject.name.strategy: io.confluent.kafka.serializers.subject.TopicNameStrategy
