server:
  port: 8089
app:
  topic: users.v1

spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/users
    username: kafka
    password: kafkaConfluent
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: validate
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl  # Use default physical naming strategy
      show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true  # Optional: Format SQL queries for readability
        jdbc:
          time_zone: UTC  # Optional: Specify JDBC time zone
  kafka:
    bootstrap-servers: ${CLOUD_BOOTSTRAP_SERVERS}
    properties:
      security.protocol: SASL_SSL
      sasl.mechanism: PLAIN
      sasl.jaas.config: org.apache.kafka.common.security.plain.PlainLoginModule required username='${CLOUD_API_KEY}' password='${CLOUD_API_SECRET}';
      schema.registry.url: ${SR_URL}
      basic.auth.credentials.source: USER_INFO
      basic.auth.user.info: ${SR_API_KEY}:${SR_API_SECRET}
    consumer:
      group-id: user-svc
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: io.confluent.kafka.serializers.KafkaAvroDeserializer
      properties:
        specific.avro.reader: true
        value.subject.name.strategy: io.confluent.kafka.serializers.subject.TopicNameStrategy

